### PR TITLE
bookpage done

### PR DESCRIPTION
**Pull request by ankithpatlolla**

### CODE REVIEW

**Comment by vamsikrishnanunna-1998** [comment]
good job displayed the page correctly

**Comment by HridayAthineni** [comment]
Good work, Page UI is good

**Comment by HridayAthineni** [comment]
Good work

**Comment by HridayAthineni** [comment]
Good work

**Review by saisrinivasreddypatlolla — COMMENTED** [review]
You have to commit every task

**Review by HridayAthineni — APPROVED** [review]
Good work!!

**Review by vamsikrishnanunna-1998 — APPROVED** [review]
Good work

**Review by saisrinivasreddypatlolla — APPROVED** [review]
Merge it. From next module you have to commit every task

**Pull request merged**
